import base64
import marshal
import secrets
import textwrap
import zlib


class ObfuscationError(Exception):
    pass


def _xor_bytes(data: bytes, key: int) -> bytes:
    return bytes(chunk ^ key for chunk in data)


def obfuscate_python_source(source: str) -> str:
    try:
        compiled = compile(source, "<pythonobfus>", "exec")
    except SyntaxError as exc:
        raise ObfuscationError(f"Input has syntax errors: {exc.msg}") from exc
    except Exception as exc:
        raise ObfuscationError("Input could not be compiled.") from exc

    try:
        payload = marshal.dumps(compiled)
        payload = zlib.compress(payload, level=9)
        key = secrets.randbelow(255) + 1
        encrypted = _xor_bytes(payload, key)
        encoded = base64.b85encode(encrypted).decode("ascii")
    except Exception as exc:
        raise ObfuscationError("Obfuscation pipeline failed.") from exc

    wrapped = "\n".join(textwrap.wrap(encoded, width=100))
    return f"""# Generated by PythonObfus
# Warning: Obfuscation raises reverse-engineering cost but is not cryptographic protection.
import base64
import marshal
import zlib

_KEY = {key}
_DATA = \"\"\"{wrapped}\"\"\"
_BIN = base64.b85decode(_DATA.encode("ascii"))
_BIN = bytes(byte ^ _KEY for byte in _BIN)
exec(marshal.loads(zlib.decompress(_BIN)))
"""
